from cmath import exp, log, log10, sin, sqrt
from math import ceil, floor
a=-5
b=49
c=4
d=2
e=2.75
f=2.35
g=-2.50
absolute=abs(a)
print(absolute)
square_root=sqrt(b)
print(square_root)
power=pow(2,2)
print(power)
power=pow(c,d)
print(power)
logarithm=log(a)
print(logarithm)
logarithm=log10(a)
print(logarithm)
exponential=exp(a)
print(exponential)
sin_value=sin(a)
print(sin_value)
round_value=round(e)
print(round_value)
round_value=round(f)
print(round_value)
round_value=round(g)
print(round_value)
ceiling=ceil(f)
print(ceiling)
floor_value=floor(f)
print(floor_value)
ceiling=ceil(g)
print(ceiling)
floor_value=floor(g)
print(floor_value)